# Generated by Django 2.0.5 on 2019-01-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190128_0543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
