# Generated by Django 2.0.5 on 2019-01-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190129_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='', upload_to='media_photo'),
        ),
    ]
