# Generated by Django 2.0.5 on 2019-01-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
