# Generated by Django 2.0.5 on 2019-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190129_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='', upload_to='photo'),
        ),
    ]
